# **Calcul Matricielle**

# Exercice1:

In [ ]:
import numpy as np

In [35]:
def creemat(n):
    A= [0] * n
    for i in range(n):
        A[i]= [0] * n
        for j in range(n):
            A[i]=[0] * n
    return A

In [54]:
def transvection(n,i,j,a):
        E = creemat(n)
        E= np.array(E)
        print(E)
        E[i-1][j-1]=1
        print(E)
        A = np.identity(n) + a*E
        return A

In [30]:
T = creemat(3,3)

In [31]:
print(T)

[[0, 0, 0], [0, 0, 0], [0, 0, 0]]


In [55]:
A = transvection(3,1,3,1)

[[0 0 0]
 [0 0 0]
 [0 0 0]]
[[0 0 1]
 [0 0 0]
 [0 0 0]]


In [56]:
A

array([[1., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.]])

# Exercice n2:

In [59]:
import numpy as np

In [83]:
def Mat_permutation(n,i,j):
    I = np.identity(n)
    A = np.copy(I)
    print(A)
    A[i-1],A[j-1]=I[j-1],I[i-1]
  
    return A
    

In [84]:
A = Mat_permutation(3,1,3)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [85]:
A

array([[0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.]])