In [1]:
import numpy as np

In [2]:
def creemat(n):
    A=[0]*n
    for i in range(n):
        A[i]=[0]*n
        for j in range(n):
            A[i]=[0]*n
    return A

In [7]:
def transvection(n,i,j,a):
    E= creemat(n)
    E= np.array(E)
    E[i-1][j-1]=1
    print(E)
    A= np.identity(n)+a*E
    return A

In [8]:
A = transvection(3,1,3,1)

[[0 0 1]
 [0 0 0]
 [0 0 0]]


In [9]:
A

array([[1., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [17]:
A=[[4,5,14],[1,11,23],[0,2,-5]]
A=np.array(A)
A

array([[ 4,  5, 14],
       [ 1, 11, 23],
       [ 0,  2, -5]])

In [18]:
T=transvection(3,1,3,1)
T

[[0 0 1]
 [0 0 0]
 [0 0 0]]


array([[1., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [19]:
C=np.dot(A,T)

In [20]:
C

array([[ 4.,  5., 18.],
       [ 1., 11., 24.],
       [ 0.,  2., -5.]])

In [21]:
D=np.dot(T,A)

In [22]:
D

array([[ 4.,  7.,  9.],
       [ 1., 11., 23.],
       [ 0.,  2., -5.]])

In [23]:
def permutation(n,i,j):
    I=np.identity(n)
    A=np.copy(I)
    print(A)
    A[i-1],A[j-1]=I[j-1],I[i-1]
    return A

In [24]:
A = permutation(3,1,3)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [25]:
A

array([[0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.]])